### ISSUE TITLE
Testing: Site testing for VolvoTrucks MX (QA & UAT)

### ISSUE THREAD

**Issue by Gonzalo-CG** [hlxsites/vg-volvotrucks-mx#1]
Testing in full all pages/sections of the site.
This issue is for both QA testing and UAT.

**Comment by Kannan-CM** [comment]
Need to handle the OneTrust by removing the Lazy load... working with Jonathatn

**Comment by BeckyMedlin** [comment]
@Kannan-CM Is that lazy load removal work being handled in this ticket or another one?

**Comment by Kannan-CM** [comment]
Hi @BeckyMedlin ,
There is another ticket for the Lazy load removal. 
@jonatan-lledo-netcentric , would you please share the ticket link here?

**Comment by jonatan-lledo-netcentric** [comment]
[this](https://github.com/hlxsites/vg-macktrucks-com/issues/638) is for all the markets to let OneTrust scan the other scripts

**Comment by Kannan-CM** [comment]
There is a separate ticket for the OneTrust for all Export markets
