### ISSUE TITLE
NFR: Configure analytics/tracking (GTM, FB Pixel)

### ISSUE THREAD

**Issue by Gonzalo-CG** [hlxsites/vg-volvotrucks-mx#6]
This is part of the GoLive activities.

**Comment by jonatan-lledo-netcentric** [comment]
linked with issue #10

**Comment by girishdigrajkar** [comment]
Correct onetrust id is applied as per issue 10 above; 
@Kannan-CM : Please confirm with OneTrust.

**Comment by Kannan-CM** [comment]
Need to allow the GTM code to load without OneTrust to scan the site..
Don't see any cookies listed in the cookie setting.

**Comment by jonatan-lledo-netcentric** [comment]
[linked](https://github.com/hlxsites/vg-macktrucks-com/issues/638) ticket related with OneTrust scan
